In [ ]:
import pyarrow.parquet as pq

table = pq.read_table("./data/val_samples.parquet")
head_df = table.slice(0, 5).to_pandas()

head_df.head()

,history_items,history_actions,target
0,"[2021897, 3172552, 1074221, 79271, 790116, 284...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1002921
1,"[1592685, 2636581, 4707299, 3528379, 1324999, ...","[1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, ...",2069846
2,"[4131518, 3812862, 3666868, 3300286, 2233225, ...","[1, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 2, 1, 1, 1, ...",899125
3,"[340379, 3376860, 4099531, 4304098, 198514, 81...","[1, 2, 3, 1, 2, 2, 2, 2, 1, 2, 1, 3, 1, 1, 2, ...",2293527
4,"[1571704, 3238962, 273647, 556913, 2283201, 20...","[1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, ...",4106658

In [5]:

table = pq.read_table("./data/train_samples.parquet")
head_df = table.slice(0, 5).to_pandas()

head_df.head()

,history_items,history_actions,target
0,"[253930, 3017005, 303012, 47489, 4364052, 1539...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",3194384
1,"[253930, 3017005, 303012, 47489, 4364052, 1539...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",3234814
2,"[253930, 3017005, 303012, 47489, 4364052, 1539...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",2682799
3,"[253930, 3017005, 303012, 47489, 4364052, 1539...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",3277782
4,"[253930, 3017005, 303012, 47489, 4364052, 1539...","[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, ...",1658896

In [9]:
table = pq.read_table("data/seq.parquet")
head_df = table.slice(0, 5).to_pandas()

head_df.head()

   user_id                                                seq
0   953188  [{'item_id': 2905777, 'action_type': 0.0, 'tim...
1   919490  [{'item_id': 2634013, 'action_type': 0.0, 'tim...
2   771916  [{'item_id': 2469426, 'action_type': 0.0, 'tim...
3   175810  [{'item_id': 2296459, 'action_type': 0.0, 'tim...
4   830016  [{'item_id': 429216, 'action_type': 1.0, 'time...

In [8]:

table = pq.read_table("local/2026-13-10-1-ei/item_embeddings.parquet")
head_df = table.slice(0, 5).to_pandas()

head_df.head()

   item_id                                          embedding
0       26  [0.123159096, -0.040801175, -0.09898063, 0.042...
1       29  [-0.034796055, -0.05296733, -0.03266963, 0.081...
2      474  [0.058568936, -0.008648781, -0.00058796536, -0...
3      964  [0.021075904, 0.07242189, -0.0042257896, 0.019...
4     1677  [0.07382083, 0.07012979, -0.032793485, 0.15899...